import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import betterTailwind from "eslint-plugin-better-tailwindcss";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Tailwind silently drops a class it doesn't know (`rounded-6`, `min-h-100dvh`); lint fails on it instead.
  // The app's own classes are known when they sit in `@layer components` in app/globals.css.
  {
    plugins: { "better-tailwindcss": betterTailwind },
    settings: { "better-tailwindcss": { entryPoint: "app/globals.css", detectComponentClasses: true } },
    rules: { "better-tailwindcss/no-unknown-classes": "error" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run typegen`; never hand-edited.
    "flotiq-api.d.ts",
  ]),
]);

export default eslintConfig;
