/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-09-29T12:24:25.900Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | Dashboardsettings
    | Namedays
    | QuizBadge
    | QuizQuestion
    | QuizTopic
    | Slogans
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | DashboardsettingsHydrated
    | NamedaysHydrated
    | QuizBadgeHydrated
    | QuizQuestionHydrated
    | QuizTopicHydrated
    | SlogansHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | DashboardsettingsHydratedTwice
    | NamedaysHydratedTwice
    | QuizBadgeHydratedTwice
    | QuizQuestionHydratedTwice
    | QuizTopicHydratedTwice
    | SlogansHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | DashboardsettingsBase
    | NamedaysBase
    | QuizBadgeBase
    | QuizQuestionBase
    | QuizTopicBase
    | SlogansBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region dashboardsettings

  export interface DashboardsettingsBase extends BaseObject<"dashboardsettings"> {
    company_name: string;
    rotate_seconds?: number;
  }

  export interface Dashboardsettings extends DashboardsettingsBase {}

  export interface DashboardsettingsHydrated extends DashboardsettingsBase {}

  export interface DashboardsettingsHydratedTwice extends DashboardsettingsBase {}

  export namespace Dashboardsettings {
    export type FilterableFields = StringWithAutocomplete<
      "company_name" | "rotate_seconds"
    >;
  }

  // #endregion

  // #region namedays

  export interface NamedaysBase extends BaseObject<"namedays"> {
    /**
     * MM-DD
     */
    date: string;
    names: string;
  }

  export interface Namedays extends NamedaysBase {}

  export interface NamedaysHydrated extends NamedaysBase {}

  export interface NamedaysHydratedTwice extends NamedaysBase {}

  export namespace Namedays {
    export type FilterableFields = StringWithAutocomplete<"date" | "names">;
  }

  // #endregion

  // #region quiz_badge

  export interface QuizBadgeBase extends BaseObject<"quiz_badge"> {
    name: string;
    glyph?: string;
    hue?: number;
    description?: string;
    ruleKey: "first" | "perfect" | "explorer" | "stars10" | "all" | "master";
  }

  export interface QuizBadge extends QuizBadgeBase {}

  export interface QuizBadgeHydrated extends QuizBadgeBase {}

  export interface QuizBadgeHydratedTwice extends QuizBadgeBase {}

  export namespace QuizBadge {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "glyph" | "hue" | "description" | "ruleKey"
    >;
  }

  // #endregion

  // #region quiz_question

  export interface QuizQuestionBase extends BaseObject<"quiz_question"> {
    topic:
      | Array<DataLink>
      | Array<QuizTopic>
      | Array<QuizTopicHydrated>
      | Array<QuizTopicHydratedTwice>
      | Array<QuizTopicBase>;
    question: string;
    answers: Array<string>;
    correctIndex: number;
    order: number;
  }

  export interface QuizQuestion extends QuizQuestionBase {
    topic: Array<DataLink>;
  }

  export interface QuizQuestionHydrated extends QuizQuestionBase {
    topic: Array<QuizTopic>;
  }

  export interface QuizQuestionHydratedTwice extends QuizQuestionBase {
    topic: Array<QuizTopicHydrated>;
  }

  export namespace QuizQuestion {
    export type FilterableFields = StringWithAutocomplete<
      | "topic"
      | "topic[*].type"
      | "topic[*].dataUrl"
      | "question"
      | "answers"
      | "correctIndex"
      | "order"
    >;
  }

  // #endregion

  // #region quiz_topic

  export interface QuizTopicBase extends BaseObject<"quiz_topic"> {
    name: string;
    slug: string;
    glyph: string;
    hue: number;
    order: number;
  }

  export interface QuizTopic extends QuizTopicBase {}

  export interface QuizTopicHydrated extends QuizTopicBase {}

  export interface QuizTopicHydratedTwice extends QuizTopicBase {}

  export namespace QuizTopic {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "slug" | "glyph" | "hue" | "order"
    >;
  }

  // #endregion

  // #region slogans

  export interface SlogansBase extends BaseObject<"slogans"> {
    text: string;
    active?: boolean;
    order?: number;
  }

  export interface Slogans extends SlogansBase {}

  export interface SlogansHydrated extends SlogansBase {}

  export interface SlogansHydratedTwice extends SlogansBase {}

  export namespace Slogans {
    export type FilterableFields = StringWithAutocomplete<
      "text" | "active" | "order"
    >;
  }

  // #endregion

  export interface FlotiqObjectAPI {
    dashboardsettings: ApiRequest<
      Dashboardsettings,
      DashboardsettingsHydrated,
      DashboardsettingsHydratedTwice,
      Dashboardsettings.FilterableFields
    >;

    namedays: ApiRequest<
      Namedays,
      NamedaysHydrated,
      NamedaysHydratedTwice,
      Namedays.FilterableFields
    >;

    quiz_badge: ApiRequest<
      QuizBadge,
      QuizBadgeHydrated,
      QuizBadgeHydratedTwice,
      QuizBadge.FilterableFields
    >;

    quiz_question: ApiRequest<
      QuizQuestion,
      QuizQuestionHydrated,
      QuizQuestionHydratedTwice,
      QuizQuestion.FilterableFields
    >;

    quiz_topic: ApiRequest<
      QuizTopic,
      QuizTopicHydrated,
      QuizTopicHydratedTwice,
      QuizTopic.FilterableFields
    >;

    slogans: ApiRequest<
      Slogans,
      SlogansHydrated,
      SlogansHydratedTwice,
      Slogans.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
